#![allow(dead_code, non_snake_case, non_upper_case_globals, unused_variables)]

use crate::template::TemplateType::*;
use crate::template::TemplateTypeClass;
use crate::terrain::LandType::*;
use crate::text::IDs::*;
use crate::theater::THEATERF;

const _slope00000001: [i8; 2] = [7, -1];
const _slope000000101: [i8; 3] = [6, 8, -1];
const _slope00000011: [i8; 3] = [6, 7, -1];
const _slope0000001: [i8; 2] = [6, -1];
const _slope000001001: [i8; 3] = [5, 8, -1];
const _slope000001: [i8; 2] = [5, -1];
const _slope000101: [i8; 3] = [3, 5, -1];
const _slope00011010000100000001000011: [i8; 8] = [3, 4, 6, 11, 19, 25, 25, -1];
const _slope00011010010100100001000011: [i8; 10] = [3, 4, 6, 9, 11, 14, 19, 24, 25, -1];
const _slope0001: [i8; 2] = [3, -1];
const _slope001001001: [i8; 4] = [2, 5, 8, -1];
const _slope00110000000011: [i8; 5] = [2, 3, 12, 13, -1];
const _slope00110010010011: [i8; 7] = [2, 3, 6, 9, 12, 13, -1];
const _slope001111001: [i8; 6] = [2, 3, 4, 5, 8, -1];
const _slope0011: [i8; 3] = [2, 3, -1];
const _slope001: [i8; 2] = [2, -1];
const _slope01000000000000000000001: [i8; 3] = [1, 22, -1];
const _slope01000000100000010000001: [i8; 5] = [1, 8, 15, 22, -1];
const _slope0111: [i8; 4] = [1, 2, 3, -1];
const _slope01: [i8; 2] = [1, -1];
const _slope1001001: [i8; 4] = [0, 3, 6, -1];
const _slope1001: [i8; 3] = [0, 3, -1];
const _slope1100000000000000001100011: [i8; 7] = [0, 1, 18, 19, 23, 24, -1];
const _slope1100001000001000001100011: [i8; 9] = [0, 1, 6, 12, 18, 19, 23, 24, -1];
const _slope1101101: [i8; 6] = [0, 1, 3, 4, 6, -1];
const _slope1101: [i8; 4] = [0, 1, 3, -1];
const _slope111: [i8; 4] = [0, 1, 2, -1];
const _slope111010011: [i8; 7] = [0, 1, 2, 4, 7, 8, -1];
const _slope11101: [i8; 5] = [0, 1, 2, 4, -1];
const _slope111111011: [i8; 9] = [0, 1, 2, 3, 4, 5, 7, 8, -1];
const _slope11111111: [i8; 9] = [0, 1, 2, 3, 4, 5, 6, 7, -1];
const _slope111111: [i8; 7] = [0, 1, 2, 3, 4, 5, -1];
const _slope1: [i8; 2] = [0, -1];

const Empty: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_CLEAR1,
    THEATERF::WINTER.bits()
        | THEATERF::DESERT.bits()
        | THEATERF::TEMPERATE.bits()
        | THEATERF::JUNGLE.bits(),
    "CLEAR1",
    TXT_CLEAR,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Clear: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_CLEAR1,
    THEATERF::WINTER.bits()
        | THEATERF::DESERT.bits()
        | THEATERF::TEMPERATE.bits()
        | THEATERF::JUNGLE.bits(),
    "CLEAR1",
    TXT_CLEAR,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Road1: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD1,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D01",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD2,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D02",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD3,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D03",
    TXT_ROAD,
    LAND_CLEAR,
    1,
    2,
    LAND_CLEAR,
    [],
);
const Road4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD4,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D04",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD5,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D05",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    4,
    LAND_CLEAR,
    [],
);
const Road6: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD6,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D06",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    3,
    LAND_CLEAR,
    [],
);
const Road7: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD7,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D07",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Road8: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD8,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D08",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Road9: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD9,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D09",
    TXT_ROAD,
    LAND_CLEAR,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Road10: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD10,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D10",
    TXT_ROAD,
    LAND_CLEAR,
    4,
    2,
    LAND_CLEAR,
    [],
);
const Road11: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD11,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D11",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    3,
    LAND_CLEAR,
    [],
);
const Road12: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD12,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D12",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road13: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD13,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D13",
    TXT_ROAD,
    LAND_CLEAR,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Road14: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD14,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D14",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road15: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD15,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D15",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road16: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD16,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D16",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road17: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD17,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D17",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Road18: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD18,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D18",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road19: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD19,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D19",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road20: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD20,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D20",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road21: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD21,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D21",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Road22: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD22,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D22",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road23: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD23,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D23",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road24: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD24,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D24",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road25: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD25,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D25",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road26: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD26,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D26",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road27: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD27,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D27",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road28: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD28,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D28",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road29: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD29,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D29",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road30: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD30,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D30",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road31: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD31,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D31",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road32: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD32,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D32",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road33: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD33,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D33",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road34: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD34,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D34",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road35: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD35,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D35",
    TXT_ROAD,
    LAND_CLEAR,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Road36: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD36,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D36",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road37: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD37,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D37",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road38: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD38,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D38",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road39: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD39,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D39",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road40: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD40,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D40",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road41: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD41,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D41",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road42: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD42,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D42",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Road43: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_ROAD43,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "D43",
    TXT_ROAD,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Water: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_WATER,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "W1",
    TXT_WATER,
    LAND_WATER,
    1,
    1,
    LAND_WATER,
    [],
);
const Water2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_WATER2,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "W2",
    TXT_WATER,
    LAND_WATER,
    2,
    2,
    LAND_WATER,
    [],
);
const Shore1: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_SHORE1,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH1",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope111111,
);
const Shore2: TemplateTypeClass<4> = TemplateTypeClass::new(
    TEMPLATE_SHORE2,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH2",
    TXT_WATER,
    LAND_ROCK,
    3,
    3,
    LAND_BEACH,
    _slope111,
);
const Shore3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE3,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH3",
    TXT_WATER,
    LAND_ROCK,
    1,
    1,
    LAND_WATER,
    [],
);
const Shore4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE4,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH4",
    TXT_WATER,
    LAND_ROCK,
    2,
    1,
    LAND_WATER,
    [],
);
const Shore5: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_SHORE5,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH5",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope111111,
);
const Shore6: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_SHORE6,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH6",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope111111,
);
const Shore7: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE7,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH7",
    TXT_WATER,
    LAND_WATER,
    2,
    2,
    LAND_BEACH,
    _slope1,
);
const Shore8: TemplateTypeClass<9> = TemplateTypeClass::new(
    TEMPLATE_SHORE8,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH8",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope11111111,
);
const Shore9: TemplateTypeClass<9> = TemplateTypeClass::new(
    TEMPLATE_SHORE9,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH9",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope111111011,
);
const Shore10: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE10,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH10",
    TXT_WATER,
    LAND_WATER,
    2,
    2,
    LAND_BEACH,
    _slope01,
);
const Shore11: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SHORE11,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH11",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope1001,
);
const Shore12: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SHORE12,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH12",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope000001001,
);
const Shore13: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE13,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH13",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_BEACH,
    _slope0000001,
);
const Shore14: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SHORE14,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH14",
    TXT_WATER,
    LAND_ROCK,
    3,
    3,
    LAND_BEACH,
    _slope00000011,
);
const Shore15: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SHORE15,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH15",
    TXT_WATER,
    LAND_ROCK,
    3,
    3,
    LAND_BEACH,
    _slope000000101,
);
const Shore16: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE16,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "SH16",
    TXT_WATER,
    LAND_ROCK,
    3,
    2,
    LAND_ROCK,
    [],
);
const Shore17: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE17,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "SH17",
    TXT_WATER,
    LAND_WATER,
    2,
    2,
    LAND_WATER,
    [],
);
const Shore18: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE18,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "SH18",
    TXT_WATER,
    LAND_WATER,
    2,
    2,
    LAND_WATER,
    [],
);
const Shore19: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE19,
    THEATERF::DESERT.bits(),
    "SH19",
    TXT_WATER,
    LAND_ROCK,
    3,
    2,
    LAND_ROCK,
    [],
);
const Shore20: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE20,
    THEATERF::DESERT.bits(),
    "SH20",
    TXT_WATER,
    LAND_ROCK,
    4,
    1,
    LAND_ROCK,
    [],
);
const Shore21: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE21,
    THEATERF::DESERT.bits(),
    "SH21",
    TXT_WATER,
    LAND_ROCK,
    3,
    1,
    LAND_ROCK,
    [],
);
const Shore22: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE22,
    THEATERF::DESERT.bits(),
    "SH22",
    TXT_WATER,
    LAND_ROCK,
    6,
    2,
    LAND_ROCK,
    [],
);
const Shore23: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE23,
    THEATERF::DESERT.bits(),
    "SH23",
    TXT_WATER,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    _slope01,
);
const Shore24: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE24,
    THEATERF::DESERT.bits(),
    "SH24",
    TXT_WATER,
    LAND_ROCK,
    3,
    3,
    LAND_CLEAR,
    _slope000001,
);
const Shore25: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE25,
    THEATERF::DESERT.bits(),
    "SH25",
    TXT_WATER,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    _slope0001,
);
const Shore26: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE26,
    THEATERF::DESERT.bits(),
    "SH26",
    TXT_WATER,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Shore27: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE27,
    THEATERF::DESERT.bits(),
    "SH27",
    TXT_WATER,
    LAND_ROCK,
    4,
    1,
    LAND_CLEAR,
    [],
);
const Shore28: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE28,
    THEATERF::DESERT.bits(),
    "SH28",
    TXT_WATER,
    LAND_ROCK,
    3,
    1,
    LAND_CLEAR,
    [],
);
const Shore29: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE29,
    THEATERF::DESERT.bits(),
    "SH29",
    TXT_WATER,
    LAND_ROCK,
    6,
    2,
    LAND_CLEAR,
    _slope00000001,
);
const Shore30: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE30,
    THEATERF::DESERT.bits(),
    "SH30",
    TXT_WATER,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Shore31: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE31,
    THEATERF::DESERT.bits(),
    "SH31",
    TXT_WATER,
    LAND_ROCK,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Shore32: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE32,
    THEATERF::TEMPERATE.bits() | THEATERF::WINTER.bits(),
    "SH32",
    TXT_WATER,
    LAND_CLEAR,
    3,
    3,
    LAND_WATER,
    _slope1,
);
const Shore33: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE33,
    THEATERF::TEMPERATE.bits() | THEATERF::WINTER.bits(),
    "SH33",
    TXT_WATER,
    LAND_CLEAR,
    3,
    3,
    LAND_WATER,
    _slope001,
);
const Shore34: TemplateTypeClass<4> = TemplateTypeClass::new(
    TEMPLATE_SHORE34,
    THEATERF::TEMPERATE.bits() | THEATERF::WINTER.bits(),
    "SH34",
    TXT_WATER,
    LAND_CLEAR,
    3,
    3,
    LAND_WATER,
    _slope001001001,
);
const Shore35: TemplateTypeClass<4> = TemplateTypeClass::new(
    TEMPLATE_SHORE35,
    THEATERF::TEMPERATE.bits() | THEATERF::WINTER.bits(),
    "SH35",
    TXT_WATER,
    LAND_CLEAR,
    3,
    3,
    LAND_WATER,
    _slope1001001,
);
const Shore36: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE36,
    THEATERF::DESERT.bits(),
    "SH36",
    TXT_WATER,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Shore37: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE37,
    THEATERF::DESERT.bits(),
    "SH37",
    TXT_WATER,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Shore38: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE38,
    THEATERF::DESERT.bits(),
    "SH38",
    TXT_WATER,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Shore39: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE39,
    THEATERF::DESERT.bits(),
    "SH39",
    TXT_WATER,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Shore40: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE40,
    THEATERF::DESERT.bits(),
    "SH40",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    _slope1,
);
const Shore41: TemplateTypeClass<6> = TemplateTypeClass::new(
    TEMPLATE_SHORE41,
    THEATERF::DESERT.bits(),
    "SH41",
    TXT_WATER,
    LAND_CLEAR,
    3,
    3,
    LAND_WATER,
    _slope1101101,
);
const Shore42: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE42,
    THEATERF::DESERT.bits(),
    "SH42",
    TXT_WATER,
    LAND_WATER,
    1,
    2,
    LAND_CLEAR,
    [],
);
const Shore43: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE43,
    THEATERF::DESERT.bits(),
    "SH43",
    TXT_WATER,
    LAND_WATER,
    1,
    3,
    LAND_CLEAR,
    [],
);
const Shore44: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE44,
    THEATERF::DESERT.bits(),
    "SH44",
    TXT_WATER,
    LAND_WATER,
    1,
    3,
    LAND_CLEAR,
    [],
);
const Shore45: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE45,
    THEATERF::DESERT.bits(),
    "SH45",
    TXT_WATER,
    LAND_WATER,
    1,
    2,
    LAND_CLEAR,
    [],
);
const Shore46: TemplateTypeClass<4> = TemplateTypeClass::new(
    TEMPLATE_SHORE46,
    THEATERF::DESERT.bits(),
    "SH46",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    _slope1101,
);
const Shore47: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE47,
    THEATERF::DESERT.bits(),
    "SH47",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Shore48: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE48,
    THEATERF::DESERT.bits(),
    "SH48",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Shore49: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE49,
    THEATERF::DESERT.bits(),
    "SH49",
    TXT_WATER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    [],
);
const Shore50: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE50,
    THEATERF::DESERT.bits(),
    "SH50",
    TXT_WATER,
    LAND_WATER,
    4,
    3,
    LAND_CLEAR,
    _slope00000001,
);
const Shore51: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE51,
    THEATERF::DESERT.bits(),
    "SH51",
    TXT_WATER,
    LAND_WATER,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Shore52: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE52,
    THEATERF::DESERT.bits(),
    "SH52",
    TXT_WATER,
    LAND_WATER,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Shore53: TemplateTypeClass<5> = TemplateTypeClass::new(
    TEMPLATE_SHORE53,
    THEATERF::DESERT.bits(),
    "SH53",
    TXT_WATER,
    LAND_WATER,
    4,
    3,
    LAND_CLEAR,
    _slope11101,
);
const Shore54: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE54,
    THEATERF::DESERT.bits(),
    "SH54",
    TXT_WATER,
    LAND_WATER,
    3,
    2,
    LAND_CLEAR,
    _slope1,
);
const Shore55: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE55,
    THEATERF::DESERT.bits(),
    "SH55",
    TXT_WATER,
    LAND_WATER,
    3,
    2,
    LAND_CLEAR,
    _slope001,
);
const Shore56: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE56,
    THEATERF::DESERT.bits(),
    "SH56",
    TXT_WATER,
    LAND_WATER,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Shore57: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE57,
    THEATERF::DESERT.bits(),
    "SH57",
    TXT_WATER,
    LAND_WATER,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Shore58: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE58,
    THEATERF::DESERT.bits(),
    "SH58",
    TXT_WATER,
    LAND_WATER,
    2,
    3,
    LAND_CLEAR,
    [],
);
const Shore59: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE59,
    THEATERF::DESERT.bits(),
    "SH59",
    TXT_WATER,
    LAND_WATER,
    2,
    3,
    LAND_CLEAR,
    _slope1,
);
const Shore60: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SHORE60,
    THEATERF::DESERT.bits(),
    "SH60",
    TXT_WATER,
    LAND_WATER,
    2,
    3,
    LAND_CLEAR,
    _slope000101,
);
const Shore61: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SHORE61,
    THEATERF::DESERT.bits(),
    "SH61",
    TXT_WATER,
    LAND_WATER,
    2,
    3,
    LAND_CLEAR,
    _slope01,
);
const Shore62: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE62,
    THEATERF::DESERT.bits(),
    "SH62",
    TXT_WATER,
    LAND_WATER,
    6,
    1,
    LAND_CLEAR,
    [],
);
const Shore63: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SHORE63,
    THEATERF::DESERT.bits(),
    "SH63",
    TXT_WATER,
    LAND_WATER,
    4,
    1,
    LAND_CLEAR,
    [],
);
const Boulder1: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER1,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "B1",
    TXT_SLOPE,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Boulder2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER2,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "B2",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    1,
    LAND_ROCK,
    [],
);
const Boulder3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER3,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "B3",
    TXT_SLOPE,
    LAND_ROCK,
    3,
    1,
    LAND_ROCK,
    [],
);
const Boulder4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER4,
    THEATERF::TEMPERATE.bits(),
    "B4",
    TXT_SLOPE,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Boulder5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER5,
    THEATERF::TEMPERATE.bits(),
    "B5",
    TXT_SLOPE,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Boulder6: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BOULDER6,
    THEATERF::TEMPERATE.bits(),
    "B6",
    TXT_SLOPE,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Slope1: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE1,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S01",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    _slope001,
);
const Slope2: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE2,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S02",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    3,
    LAND_CLEAR,
    _slope01,
);
const Slope3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE3,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S03",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE4,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S04",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE5,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S05",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope6: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE6,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S06",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    3,
    LAND_CLEAR,
    _slope1,
);
const Slope7: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE7,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S07",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope8: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE8,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S08",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    _slope01,
);
const Slope9: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE9,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S09",
    TXT_SLOPE,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    _slope0001,
);
const Slope10: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE10,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S10",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope11: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE11,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S11",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope12: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE12,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S12",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope13: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE13,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S13",
    TXT_SLOPE,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    _slope000001,
);
const Slope14: TemplateTypeClass<4> = TemplateTypeClass::new(
    TEMPLATE_SLOPE14,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S14",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    _slope0111,
);
const Slope15: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE15,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S15",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_CLEAR,
    _slope01,
);
const Slope16: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE16,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S16",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    3,
    LAND_ROCK,
    [],
);
const Slope17: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE17,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S17",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope18: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE18,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S18",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope19: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE19,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S19",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope20: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE20,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S20",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    3,
    LAND_CLEAR,
    _slope000001,
);
const Slope21: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE21,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S21",
    TXT_SLOPE,
    LAND_ROCK,
    1,
    2,
    LAND_ROCK,
    [],
);
const Slope22: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE22,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S22",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    1,
    LAND_ROCK,
    [],
);
const Slope23: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_SLOPE23,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S23",
    TXT_SLOPE,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    _slope000001,
);
const Slope24: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE24,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S24",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope25: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE25,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S25",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope26: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE26,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S26",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope27: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_SLOPE27,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S27",
    TXT_SLOPE,
    LAND_ROCK,
    3,
    2,
    LAND_CLEAR,
    _slope0011,
);
const Slope28: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE28,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S28",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope29: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE29,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S29",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope30: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE30,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S30",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope31: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE31,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S31",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope32: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE32,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S32",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope33: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE33,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S33",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope34: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE34,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S34",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope35: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE35,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S35",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope36: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE36,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S36",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope37: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE37,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S37",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Slope38: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_SLOPE38,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "S38",
    TXT_SLOPE,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Brush1: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH1,
    THEATERF::DESERT.bits(),
    "BR1",
    TXT_BRUSH,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Brush2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH2,
    THEATERF::DESERT.bits(),
    "BR2",
    TXT_BRUSH,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Brush3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH3,
    THEATERF::DESERT.bits(),
    "BR3",
    TXT_BRUSH,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Brush4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH4,
    THEATERF::DESERT.bits(),
    "BR4",
    TXT_BRUSH,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Brush5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH5,
    THEATERF::DESERT.bits(),
    "BR5",
    TXT_BRUSH,
    LAND_ROCK,
    1,
    1,
    LAND_ROCK,
    [],
);
const Brush6: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH6,
    THEATERF::DESERT.bits(),
    "BR6",
    TXT_BRUSH,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Brush7: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH7,
    THEATERF::DESERT.bits(),
    "BR7",
    TXT_BRUSH,
    LAND_ROCK,
    2,
    2,
    LAND_ROCK,
    [],
);
const Brush8: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH8,
    THEATERF::DESERT.bits(),
    "BR8",
    TXT_BRUSH,
    LAND_ROCK,
    3,
    2,
    LAND_ROCK,
    [],
);
const Brush9: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH9,
    THEATERF::DESERT.bits(),
    "BR9",
    TXT_BRUSH,
    LAND_ROCK,
    3,
    2,
    LAND_ROCK,
    [],
);
const Brush10: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_BRUSH10,
    THEATERF::DESERT.bits(),
    "BR10",
    TXT_BRUSH,
    LAND_ROCK,
    2,
    1,
    LAND_ROCK,
    [],
);
const Patch1: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH1,
    THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P01",
    TXT_PATCH,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Patch2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH2,
    THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P02",
    TXT_PATCH,
    LAND_ROCK,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Patch3: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH3,
    THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P03",
    TXT_PATCH,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Patch4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH4,
    THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P04",
    TXT_PATCH,
    LAND_ROCK,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Patch5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH5,
    THEATERF::DESERT.bits(),
    "P05",
    TXT_PATCH,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Patch6: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH6,
    THEATERF::DESERT.bits(),
    "P06",
    TXT_PATCH,
    LAND_CLEAR,
    6,
    4,
    LAND_CLEAR,
    [],
);
const Patch7: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH7,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P07",
    TXT_PATCH,
    LAND_CLEAR,
    4,
    2,
    LAND_CLEAR,
    [],
);
const Patch8: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH8,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits() | THEATERF::DESERT.bits(),
    "P08",
    TXT_PATCH,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Patch13: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH13,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "P13",
    TXT_PATCH,
    LAND_CLEAR,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Patch14: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH14,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "P14",
    TXT_PATCH,
    LAND_CLEAR,
    2,
    1,
    LAND_CLEAR,
    [],
);
const Patch15: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH15,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "P15",
    TXT_PATCH,
    LAND_CLEAR,
    1,
    1,
    LAND_CLEAR,
    [],
);
const Patch16: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH16,
    THEATERF::WINTER.bits(),
    "P16",
    TXT_PATCH,
    LAND_CLEAR,
    2,
    2,
    LAND_CLEAR,
    [],
);
const Patch17: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH17,
    THEATERF::WINTER.bits(),
    "P17",
    TXT_PATCH,
    LAND_CLEAR,
    4,
    2,
    LAND_CLEAR,
    [],
);
const Patch18: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH18,
    THEATERF::WINTER.bits(),
    "P18",
    TXT_PATCH,
    LAND_CLEAR,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Patch19: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH19,
    THEATERF::WINTER.bits(),
    "P19",
    TXT_PATCH,
    LAND_CLEAR,
    4,
    3,
    LAND_CLEAR,
    [],
);
const Patch20: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_PATCH20,
    THEATERF::WINTER.bits(),
    "P20",
    TXT_PATCH,
    LAND_CLEAR,
    4,
    3,
    LAND_CLEAR,
    [],
);
const River1: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER1,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV01",
    TXT_RIVER,
    LAND_WATER,
    5,
    4,
    LAND_CLEAR,
    [],
);
const River2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER2,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV02",
    TXT_RIVER,
    LAND_WATER,
    5,
    3,
    LAND_ROCK,
    [],
);
const River3: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_RIVER3,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV03",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_CLEAR,
    _slope00000001,
);
const River4: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER4,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV04",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_ROCK,
    [],
);
const River5: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER5,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV05",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_ROCK,
    [],
);
const River6: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER6,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV06",
    TXT_RIVER,
    LAND_WATER,
    3,
    2,
    LAND_ROCK,
    [],
);
const River7: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER7,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV07",
    TXT_RIVER,
    LAND_WATER,
    3,
    2,
    LAND_ROCK,
    [],
);
const River8: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER8,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV08",
    TXT_RIVER,
    LAND_WATER,
    2,
    2,
    LAND_ROCK,
    [],
);
const River9: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER9,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV09",
    TXT_RIVER,
    LAND_WATER,
    2,
    2,
    LAND_ROCK,
    [],
);
const River10: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER10,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV10",
    TXT_RIVER,
    LAND_WATER,
    2,
    2,
    LAND_ROCK,
    [],
);
const River11: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER11,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV11",
    TXT_RIVER,
    LAND_WATER,
    2,
    2,
    LAND_ROCK,
    [],
);
const River12: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER12,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV12",
    TXT_RIVER,
    LAND_WATER,
    3,
    4,
    LAND_ROCK,
    [],
);
const River13: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER13,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "RV13",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_ROCK,
    [],
);
const River14: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER14,
    THEATERF::DESERT.bits(),
    "RV14",
    TXT_RIVER,
    LAND_WATER,
    4,
    3,
    LAND_ROCK,
    [],
);
const River15: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER15,
    THEATERF::DESERT.bits(),
    "RV15",
    TXT_RIVER,
    LAND_WATER,
    4,
    3,
    LAND_ROCK,
    [],
);
const River16: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER16,
    THEATERF::DESERT.bits(),
    "RV16",
    TXT_RIVER,
    LAND_WATER,
    6,
    4,
    LAND_ROCK,
    [],
);
const River17: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER17,
    THEATERF::DESERT.bits(),
    "RV17",
    TXT_RIVER,
    LAND_WATER,
    6,
    5,
    LAND_ROCK,
    [],
);
const River18: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER18,
    THEATERF::DESERT.bits(),
    "RV18",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_ROCK,
    [],
);
const River19: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER19,
    THEATERF::DESERT.bits(),
    "RV19",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_ROCK,
    [],
);
const River20: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER20,
    THEATERF::DESERT.bits(),
    "RV20",
    TXT_RIVER,
    LAND_WATER,
    6,
    8,
    LAND_ROCK,
    [],
);
const River21: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER21,
    THEATERF::DESERT.bits(),
    "RV21",
    TXT_RIVER,
    LAND_WATER,
    5,
    8,
    LAND_ROCK,
    [],
);
const River22: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER22,
    THEATERF::DESERT.bits(),
    "RV22",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_ROCK,
    [],
);
const River23: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER23,
    THEATERF::DESERT.bits(),
    "RV23",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_ROCK,
    [],
);
const River24: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER24,
    THEATERF::DESERT.bits(),
    "RV24",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_ROCK,
    [],
);
const River25: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_RIVER25,
    THEATERF::DESERT.bits(),
    "RV25",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_ROCK,
    [],
);
const Ford1: TemplateTypeClass<6> = TemplateTypeClass::new(
    TEMPLATE_FORD1,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "FORD1",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    _slope001111001,
);
const Ford2: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_FORD2,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "FORD2",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    _slope111010011,
);
const Falls1: TemplateTypeClass<2> = TemplateTypeClass::new(
    TEMPLATE_FALLS1,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "FALLS1",
    TXT_RIVER,
    LAND_WATER,
    3,
    3,
    LAND_CLEAR,
    _slope1,
);
const Falls2: TemplateTypeClass<0> = TemplateTypeClass::new(
    TEMPLATE_FALLS2,
    THEATERF::WINTER.bits() | THEATERF::DESERT.bits() | THEATERF::TEMPERATE.bits(),
    "FALLS2",
    TXT_RIVER,
    LAND_WATER,
    3,
    2,
    LAND_CLEAR,
    [],
);
const Bridge1: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE1,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "BRIDGE1",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_CLEAR,
    _slope00110010010011,
);
const Bridge1d: TemplateTypeClass<5> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE1D,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "BRIDGE1D",
    TXT_RIVER,
    LAND_WATER,
    4,
    4,
    LAND_CLEAR,
    _slope00110000000011,
);
const Bridge2: TemplateTypeClass<9> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE2,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "BRIDGE2",
    TXT_RIVER,
    LAND_WATER,
    5,
    5,
    LAND_CLEAR,
    _slope1100001000001000001100011,
);
const Bridge2d: TemplateTypeClass<7> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE2D,
    THEATERF::WINTER.bits() | THEATERF::TEMPERATE.bits(),
    "BRIDGE2D",
    TXT_RIVER,
    LAND_WATER,
    5,
    5,
    LAND_CLEAR,
    _slope1100000000000000001100011,
);
const Bridge3: TemplateTypeClass<10> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE3,
    THEATERF::DESERT.bits(),
    "BRIDGE3",
    TXT_RIVER,
    LAND_WATER,
    6,
    5,
    LAND_CLEAR,
    _slope00011010010100100001000011,
);
const Bridge3d: TemplateTypeClass<8> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE3D,
    THEATERF::DESERT.bits(),
    "BRIDGE3D",
    TXT_RIVER,
    LAND_WATER,
    6,
    5,
    LAND_CLEAR,
    _slope00011010000100000001000011,
);
const Bridge4: TemplateTypeClass<5> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE4,
    THEATERF::DESERT.bits(),
    "BRIDGE4",
    TXT_RIVER,
    LAND_WATER,
    6,
    4,
    LAND_CLEAR,
    _slope01000000100000010000001,
);
const Bridge4d: TemplateTypeClass<3> = TemplateTypeClass::new(
    TEMPLATE_BRIDGE4D,
    THEATERF::DESERT.bits(),
    "BRIDGE4D",
    TXT_RIVER,
    LAND_WATER,
    6,
    4,
    LAND_CLEAR,
    _slope01000000000000000000001,
);
