#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_variables
)]

#[repr(u16)]
pub enum IDs {
    //TXT_NONE                 	0  	//
    TXT_CREDIT_FORMAT = 1,                             // %3d.%02d
    TXT_BUTTON_UPGRADE = 2,                            // Upgrade
    TXT_UPGRADE = 3,                                   // Upgrade Structure
    TXT_UPGRADE_BUTTON = 4,                            // Upgrade
    TXT_BUTTON_SELL = 5,                               // Sell
    TXT_SELL = 6,                                      // Sell Structure
    TXT_DEMOLISH = 7,                                  // Demolish Structure
    TXT_BUTTON_REPAIR = 8,                             // Repair
    TXT_REPAIR = 9,                                    // Repair Structure
    TXT_REPAIR_BUTTON = 10,                            // Repair
    TXT_YOU = 11,                                      // You:
    TXT_ENEMY = 12,                                    // Enemy:
    TXT_BUILD_DEST = 13,                               // Buildings Destroyed By
    TXT_UNIT_DEST = 14,                                // Units Destroyed By
    TXT_TIB_HARV = 15,                                 // Tiberium Harvested By
    TXT_SCORE_1 = 16,                                  // Score: %d
    TXT_RANK_OF = 17,                                  // You have attained the rank
    TXT_YES = 18,                                      // Yes
    TXT_NO = 19,                                       // No
    TXT_READY = 20,                                    // Ready
    TXT_HOLDING = 21,                                  // Holding
    TXT_SCENARIO_WON = 22,                             // Accomplished
    TXT_SCENARIO_LOST = 23,                            // Failed
    TXT_CHOOSE_SIDE = 24,                              // Choose Your Side
    TXT_START_NEW_GAME = 25,                           // Start New Game
    TXT_INTRO = 26,                                    // Intro & Sneak Peek
    TXT_CANCEL = 27,                                   // Cancel
    TXT_ROCK = 28,                                     // Rock
    TXT_CHOAM_RESUME = 29,                             // Resume Game
    TXT_CHOAM_BUILD_THIS = 30,                         // Build This
    TXT_THANK_YOU = 31,                                // Thank you for playing
    TXT_FAME = 32,                                     // Hall of Fame
    TXT_GDI = 33,                                      // Global Defense Initiative
    TXT_NOD = 34,                                      // Brotherhood of Nod
    TXT_CIVILIAN = 35,                                 // Civilian
    TXT_JP = 36,                                       // Containment Team
    TXT_OK = 37,                                       // OK
    TXT_TREE = 38,                                     // Tree
    TXT_LEFT = 39,                                     // 
    TXT_RIGHT = 40,                                    // 
    TXT_UP = 41,                                       // 
    TXT_DOWN = 42,                                     // 
    TXT_CLEAR_MAP = 43,                                // Clear the map
    TXT_INHERIT_MAP = 44,                              // Inherit previous map
    TXT_CLEAR = 45,                                    // Clear
    TXT_WATER = 46,                                    // Water
    TXT_ROAD = 47,                                     // Road
    TXT_TILE = 48,                                     // Tile Object
    TXT_SLOPE = 49,                                    // Slope
    TXT_BRUSH = 50,                                    // Brush
    TXT_PATCH = 51,                                    // Patch
    TXT_RIVER = 52,                                    // River
    TXT_LOAD_MISSION = 53,                             // Load Mission
    TXT_SAVE_MISSION = 54,                             // Save Mission
    TXT_DELETE_MISSION = 55,                           // Delete Mission
    TXT_LOAD_BUTTON = 56,                              // Load
    TXT_SAVE_BUTTON = 57,                              // Save
    TXT_DELETE_BUTTON = 58,                            // Delete
    TXT_GAME_CONTROLS = 59,                            // Game Controls
    TXT_SOUND_CONTROLS = 60,                           // Sound Controls
    TXT_RESUME_MISSION = 61,                           // Resume Mission
    TXT_VISUAL_CONTROLS = 62,                          // Visual Controls
    TXT_QUIT_MISSION = 63,                             // Abort Mission
    TXT_EXIT_GAME = 64,                                // Exit Game
    TXT_OPTIONS = 65,                                  // Options
    TXT_TIBERIUM = 66,                                 // Tiberium
    TXT_TIBERIUM_ON = 67,                              // Tiberium On
    TXT_TIBERIUM_OFF = 68,                             // Tiberium Off
    TXT_SQUISH = 69,                                   // Squish mark
    TXT_CRATER = 70,                                   // Crater
    TXT_SCORCH = 71,                                   // Scorch Mark
    TXT_BRIGHTNESS = 72,                               // BRIGHTNESS:
    TXT_MUSIC = 73,                                    // MUSIC VOLUME
    TXT_VOLUME = 74,                                   // SOUND VOLUME
    TXT_TINT = 75,                                     // TINT:
    TXT_CONTRAST = 76,                                 // CONTRAST:
    TXT_SPEED = 77,                                    // GAME SPEED:
    TXT_SCROLLRATE = 78,                               // SCROLL RATE:
    TXT_COLOR = 79,                                    // COLOR:
    TXT_RETURN_TO_GAME = 80,                           // Return to game
    TXT_ENEMY_SOLDIER = 81,                            // Enemy Soldier
    TXT_ENEMY_VEHICLE = 82,                            // Enemy Vehicle
    TXT_ENEMY_STRUCTURE = 83,                          // Enemy Structure
    TXT_FTANK = 84,                                    // Flame Tank
    TXT_STANK = 85,                                    // Stealth Tank
    TXT_LTANK = 86,                                    // Light Tank
    TXT_MTANK = 87,                                    // Med. Tank
    TXT_HTANK = 88,                                    // Mammoth Tank
    TXT_DUNE_BUGGY = 89,                               // Nod Buggy
    TXT_SAM = 90,                                      // SAM Site
    TXT_EYE = 91,                                      // Advanced Com. Center
    TXT_MLRS = 92,                                     // Rocket Launcher
    TXT_MHQ = 93,                                      // Mobile HQ
    TXT_JEEP = 94,                                     // Hum-vee
    TXT_TRANS = 95,                                    // Transport Helicopter
    TXT_A10 = 96,                                      // A10
    TXT_C17 = 97,                                      // C17
    TXT_HARVESTER = 98,                                // Harvester
    TXT_ARTY = 99,                                     // Artillery
    TXT_MSAM = 100,                                    // S.S.M. Launcher
    TXT_E1 = 101,                                      // Minigunner
    TXT_E2 = 102,                                      // Grenadier
    TXT_E3 = 103,                                      // Bazooka
    TXT_E4 = 104,                                      // Flamethrower
    TXT_E5 = 105,                                      // Chem-warrior
    TXT_RAMBO = 106,                                   // Commando
    TXT_HOVER = 107,                                   // Hovercraft
    TXT_HELI = 108,                                    // Attack Helicopter
    TXT_ORCA = 109,                                    // Orca
    TXT_APC = 110,                                     // APC
    TXT_GUARD_TOWER = 111,                             // Guard Tower
    TXT_COMMAND = 112,                                 // Communications Center
    TXT_HELIPAD = 113,                                 // Helicopter Pad
    TXT_AIRSTRIP = 114,                                // Airstrip
    TXT_STORAGE = 115,                                 // Tiberium Silo
    TXT_CONST_YARD = 116,                              // Construction Yard
    TXT_REFINERY = 117,                                // Tiberium Refinery
    TXT_CIV1 = 118,                                    // Church
    TXT_CIV2 = 119,                                    // Han's and Gretel's
    TXT_CIV3 = 120,                                    // Hewitt's Manor
    TXT_CIV4 = 121,                                    // Ricktor's House
    TXT_CIV5 = 122,                                    // Gretchin's House
    TXT_CIV6 = 123,                                    // The Barn
    TXT_CIV7 = 124,                                    // Damon's pub
    TXT_CIV8 = 125,                                    // Fran's House
    TXT_CIV9 = 126,                                    // Music Factory
    TXT_CIV10 = 127,                                   // Toymaker's
    TXT_CIV11 = 128,                                   // Ludwig's House
    TXT_CIV12 = 129,                                   // Haystacks
    TXT_CIV13 = 130,                                   // Haystack
    TXT_CIV14 = 131,                                   // Wheat Field
    TXT_CIV15 = 132,                                   // Fallow Field
    TXT_CIV16 = 133,                                   // Corn Field
    TXT_CIV17 = 134,                                   // Celery Field
    TXT_CIV18 = 135,                                   // Potato Field
    TXT_CIV20 = 136,                                   // Sala's House
    TXT_CIV21 = 137,                                   // Abdul's House
    TXT_CIV22 = 138,                                   // Pablo's Wicked Pub
    TXT_CIV23 = 139,                                   // Village Well
    TXT_CIV24 = 140,                                   // Camel Trader
    TXT_CIV25 = 141,                                   // Church
    TXT_CIV26 = 142,                                   // Ali's House
    TXT_CIV27 = 143,                                   // Trader Ted's
    TXT_CIV28 = 144,                                   // Menelik's House
    TXT_CIV29 = 145,                                   // Prestor John's House
    TXT_CIV30 = 146,                                   // Village Well
    TXT_CIV31 = 147,                                   // Witch Doctor's Hut
    TXT_CIV32 = 148,                                   // Rikitikitembo's Hut
    TXT_CIV33 = 149,                                   // Roarke's Hut
    TXT_CIV34 = 150,                                   // Mubasa's Hut
    TXT_CIV35 = 151,                                   // Aksum's Hut
    TXT_CIV36 = 152,                                   // Mambo's Hut
    TXT_CIV37 = 153,                                   // The Studio
    TXT_CIVMISS = 154,                                 // Technology Center
    TXT_TURRET = 155,                                  // Gun Turret
    TXT_GUNBOAT = 156,                                 // Gun Boat
    TXT_MCV = 157,                                     // Mobile Construction Yard
    TXT_BIKE = 158,                                    // Recon Bike
    TXT_POWER = 159,                                   // Power Plant
    TXT_ADVANCED_POWER = 160,                          // Advanced Power Plant
    TXT_HOSPITAL = 161,                                // Hospital
    TXT_BARRACKS = 162,                                // Barracks
    TXT_CONCRETE = 163,                                // Concrete
    TXT_PUMP = 164,                                    // Oil Pump
    TXT_TANKER = 165,                                  // Oil Tanker
    TXT_SANDBAG_WALL = 166,                            // Sandbag Wall
    TXT_CYCLONE_WALL = 167,                            // Chain Link Fence
    TXT_BRICK_WALL = 168,                              // Concrete Wall
    TXT_BARBWIRE_WALL = 169,                           // Barbwire Fence
    TXT_WOOD_WALL = 170,                               // Wood Fence
    TXT_WEAPON_FACTORY = 171,                          // Weapons Factory
    TXT_AGUARD_TOWER = 172,                            // Advanced Guard Tower
    TXT_OBELISK = 173,                                 // Obelisk Guard Tower
    TXT_BIO_LAB = 174,                                 // Bio-Research Laboratory
    TXT_HAND = 175,                                    // Hand of Nod
    TXT_TEMPLE = 176,                                  // Temple of Nod
    TXT_FIX_IT = 177,                                  // Repair Bay
    TXT_TAB_SIDEBAR = 178,                             // Sidebar
    TXT_TAB_BUTTON_CONTROLS = 179,                     // Options
    TXT_TAB_BUTTON_DATABASE = 180,                     // Database
    TXT_SHADOW = 181,                                  // Unrevealed Terrain
    TXT_OPTIONS_MENU = 182,                            // Options Menu
    TXT_STOP = 183,                                    // STOP
    TXT_PLAY = 184,                                    // PLAY
    TXT_SHUFFLE = 185,                                 // SHUFFLE
    TXT_REPEAT = 186,                                  // REPEAT
    TXT_MUSIC_VOLUME = 187,                            // Music volume:
    TXT_SOUND_VOLUME = 188,                            // Sound volume:
    TXT_ON = 189,                                      // On
    TXT_OFF = 190,                                     // Off
    TXT_THEME_AOI = 191,                               // Act On Instinct
    TXT_THEME_TROUBLE = 192,                           // Looks Like Trouble
    TXT_THEME_IND = 193,                               // Industrial
    TXT_THEME_ROUT = 194,                              // Reaching Out
    TXT_THEME_OTP = 195,                               // On The Prowl
    TXT_THEME_PRP = 196,                               // Prepare For Battle
    TXT_THEME_JUSTDOIT = 197,                          // Just Do It!
    TXT_THEME_LINEFIRE = 198,                          // In The Line Of Fire
    TXT_THEME_MARCH = 199,                             // March To Doom
    TXT_THEME_STOPTHEM = 200,                          // Deception
    TXT_THEME_CCTHANG = 201,                           // C&C Thang
    TXT_THEME_BEFEARED = 202,                          // Enemies To Be Feared
    TXT_THEME_WARFARE = 203,                           // Warfare
    TXT_THEME_FWP = 204,                               // Fight, Win, Prevail
    TXT_THEME_DIE = 205,                               // Die!!
    TXT_THEME_NOMERCY = 206,                           // No Mercy
    TXT_THEME_TARGET = 207,                            // Mechanical Man
    TXT_THEME_IAM = 208,                               // I Am
    TXT_THEME_WIN1 = 209,                              // Great Shot!
    TXT_MULTIPLAYER_GAME = 210,                        // Multiplayer Game
    TXT_NO_FILES = 211,                                // No files available
    TXT_DELETE_SINGLE_FILE = 212,                      // Do you want to delete this
    TXT_DELETE_MULTIPLE_FILES = 213,                   // Do you want to delete %d
    TXT_RESET_MENU = 214,                              // Reset Values
    TXT_CONFIRMATION = 215,                            // Confirmation
    TXT_CONFIRM_EXIT = 216,                            // Do you want to abort the
    TXT_MISSION_DESCRIPTION = 217,                     // Mission Description
    TXT_C1 = 218,                                      // Joe
    TXT_C2 = 219,                                      // Bill
    TXT_C3 = 220,                                      // Shelly
    TXT_C4 = 221,                                      // Maria
    TXT_C5 = 222,                                      // Eydie
    TXT_C6 = 223,                                      // Dave
    TXT_C7 = 224,                                      // Phil
    TXT_C8 = 225,                                      // Dwight
    TXT_C9 = 226,                                      // Erik
    TXT_MOEBIUS = 227,                                 // Dr. Moebius
    TXT_BIB = 228,                                     // Road Bib
    TXT_FASTER = 229,                                  // Faster
    TXT_SLOWER = 230,                                  // Slower
    TXT_ION_CANNON = 231,                              // Ion Cannon
    TXT_NUKE_STRIKE = 232,                             // Nuclear Strike
    TXT_AIR_STRIKE = 233,                              // Air Strike
    TXT_TREX = 234,                                    // Tyrannosaurus Rex
    TXT_TRIC = 235,                                    // Triceratops
    TXT_RAPT = 236,                                    // Velociraptor
    TXT_STEG = 237,                                    // Stegasaurus
    TXT_STEEL_CRATE = 238,                             // Steel Crate
    TXT_WOOD_CRATE = 239,                              // Wood Crate
    TXT_FLAG_SPOT = 240,                               // Flag Location
    TXT_G_D_I = 241,                                   // GDI
    TXT_N_O_D = 242,                                   // NOD
    TXT_UNABLE_READ_SCENARIO = 243,                    // Unable to read scenario!
    TXT_ERROR_LOADING_GAME = 244,                      // Error loading game!
    TXT_OBSOLETE_SAVEGAME = 245,                       // Obsolete saved game.
    TXT_MUSTENTER_DESCRIPTION = 246,                   // You must enter a
    TXT_ERROR_SAVING_GAME = 247,                       // Error saving game!
    TXT_DELETE_FILE_QUERY = 248,                       // Delete this file?
    TXT_EMPTY_SLOT = 249,                              // [EMPTY SLOT]
    TXT_SELECT_MPLAYER_GAME = 250,                     // Select Multiplayer Game
    TXT_MODEM_SERIAL = 251,                            // Modem/Serial
    TXT_NETWORK = 252,                                 // Network
    TXT_INIT_NET_ERROR = 253,                          // Unable to initialize
    TXT_JOIN_NETWORK_GAME = 254,                       // Join Network Game
    TXT_NEW = 255,                                     // New
    TXT_JOIN = 256,                                    // Join
    TXT_SEND_MESSAGE = 257,                            // Send Message
    TXT_YOUR_NAME = 258,                               // Your Name:
    TXT_SIDE_COLON = 259,                              // Side:
    TXT_COLOR_COLON = 260,                             // Color:
    TXT_GAMES = 261,                                   // Games
    TXT_PLAYERS = 262,                                 // Players
    TXT_SCENARIO_COLON = 263,                          // Scenario:
    TXT_NOT_FOUND = 264,                               // >> NOT FOUND <<
    TXT_START_CREDITS_COLON = 265,                     // Starting Credits:
    TXT_BASES_COLON = 266,                             // Bases:
    TXT_TIBERIUM_COLON = 267,                          // Tiberium:
    TXT_CRATES_COLON = 268,                            // Crates:
    TXT_AI_PLAYERS_COLON = 269,                        // AI Players:
    TXT_REQUEST_DENIED = 270,                          // Request denied.
    TXT_UNABLE_PLAY_WAAUGH = 271,                      // Unable to play; scenario
    TXT_NOTHING_TO_JOIN = 272,                         // Nothing to join!
    TXT_NAME_ERROR = 273,                              // You must enter a name!
    TXT_DUPENAMES_NOTALLOWED = 274,                    // Duplicate names are not
    TXT_YOURGAME_OUTDATED = 275,                       // Your game version is
    TXT_DESTGAME_OUTDATED = 276,                       // Destination game version is
    TXT_THATGUYS_GAME = 277,                           // %s's Game
    TXT_THATGUYS_GAME_BRACKET = 278,                   // [%s's Game]
    TXT_NETGAME_SETUP = 279,                           // Network Game Setup
    TXT_REJECT = 280,                                  // Reject
    TXT_CANT_REJECT_SELF = 281,                        // You can't reject yourself!
    TXT_SELECT_PLAYER_REJECT = 282,                    // You must select a player to
    TXT_BASES_ON = 283,                                // Bases On
    TXT_BASES_OFF = 284,                               // Bases Off
    TXT_CRATES_ON = 285,                               // Crates On
    TXT_CRATES_OFF = 286,                              // Crates Off
    TXT_AI_PLAYERS_ON = 287,                           // AI Players On
    TXT_AI_PLAYERS_OFF = 288,                          // AI Players Off
    TXT_SCENARIOS = 289,                               // Scenarios
    TXT_START_CREDITS = 290,                           // Starting Credits
    TXT_ONLY_ONE = 291,                                // Only one player?
    TXT_OOPS = 292,                                    // Oops!
    TXT_TO = 293,                                      // To %s:
    TXT_TO_ALL = 294,                                  // To All:
    TXT_MESSAGE = 295,                                 // Message:
    TXT_CONNECTION_LOST = 296,                         // Connection to %s lost!
    TXT_LEFT_GAME = 297,                               // %s has left the game.
    TXT_PLAYER_DEFEATED = 298,                         // %s has been defeated!
    TXT_WAITING_CONNECT = 299,                         // Waiting to Connect...
    TXT_NULL_CONNERR_CHECK_CABLES = 300,               // Connection error! Check
    TXT_MODEM_CONNERR_REDIALING = 301,                 // Connection
    TXT_MODEM_CONNERR_WAITING = 302,                   // Connection error! Waiting
    TXT_SELECT_SERIAL_GAME = 303,                      // Select Serial Game
    TXT_DIAL_MODEM = 304,                              // Dial Modem
    TXT_ANSWER_MODEM = 305,                            // Answer Modem
    TXT_NULL_MODEM = 306,                              // Null Modem
    TXT_SETTINGS = 307,                                // Settings
    TXT_PORT_COLON = 308,                              // Port:
    TXT_IRQ_COLON = 309,                               // IRQ:
    TXT_BAUD_COLON = 310,                              // Baud:
    TXT_INIT_STRING = 311,                             // Init String:
    TXT_CWAIT_STRING = 312,                            // Call Waiting String:
    TXT_TONE_BUTTON = 313,                             // Tone Dialing
    TXT_PULSE_BUTTON = 314,                            // Pulse Dialing
    TXT_HOST_SERIAL_GAME = 315,                        // Host Serial Game
    TXT_OPPONENT_COLON = 316,                          // Opponent:
    TXT_USER_SIGNED_OFF = 317,                         // User signed off!
    TXT_JOIN_SERIAL_GAME = 318,                        // Join Serial Game
    TXT_PHONE_LIST = 319,                              // Phone List
    TXT_ADD = 320,                                     // Add
    TXT_EDIT = 321,                                    // Edit
    TXT_DIAL = 322,                                    // Dial
    TXT_DEFAULT = 323,                                 // Default
    TXT_DEFAULT_SETTINGS = 324,                        // Default Settings
    TXT_CUSTOM_SETTINGS = 325,                         // Custom Settings
    TXT_PHONE_LISTING = 326,                           // Phone Listing
    TXT_NAME_COLON = 327,                              // Name:
    TXT_NUMBER_COLON = 328,                            // Number:
    TXT_UNABLE_FIND_MODEM = 329,                       // Unable to find modem. Check
    TXT_NO_CARRIER = 330,                              // No carrier.
    TXT_LINE_BUSY = 331,                               // Line busy.
    TXT_NUMBER_INVALID = 332,                          // Number invalid.
    TXT_SYSTEM_NOT_RESPONDING = 333,                   // Other system not
    TXT_OUT_OF_SYNC = 334,                             // Games are out of sync!
    TXT_PACKET_TOO_LATE = 335,                         // Packet received too late!
    TXT_PLAYER_LEFT_GAME = 336,                        // Other player has left the
    TXT_FROM = 337,                                    // From %s:%s
    TXT_MAP_P01 = 338,                                 // 2,728,000
    TXT_MAP_P02 = 339,                                 // 38,385,000
    TXT_MAP_P03 = 340,                                 // 10,373,000
    TXT_MAP_P04 = 341,                                 // 51,994,000
    TXT_MAP_P05 = 342,                                 // 80,387,000
    TXT_MAP_P06 = 343,                                 // 10,400,000
    TXT_MAP_P07 = 344,                                 // 5,300,000
    TXT_MAP_P08 = 345,                                 // 7,867,000
    TXT_MAP_P09 = 346,                                 // 10,333,000
    TXT_MAP_P10 = 347,                                 // 1,974,000
    TXT_MAP_P11 = 348,                                 // 23,169,000
    TXT_MAP_P12 = 349,                                 // 10,064,000
    TXT_MAP_P13 = 350,                                 // 3,285,000
    TXT_MAP_P14 = 351,                                 // 8,868,000
    TXT_MAP_P15 = 352,                                 // 10,337,000
    TXT_MAP_P16 = 353,                                 // 4,365,000
    TXT_MAP_P17 = 354,                                 // 1,607,000
    TXT_MAP_P18 = 355,                                 // 4,485,000
    TXT_MAP_P19 = 356,                                 // 56,386,000
    TXT_MAP_P20 = 357,                                 // 28,305,000
    TXT_MAP_P21 = 358,                                 // 5,238,000
    TXT_MAP_P22 = 359,                                 // 2,059,000
    TXT_MAP_P23 = 360,                                 // 13,497,000
    TXT_MAP_P24 = 361,                                 // 4,997,000
    TXT_MAP_P25 = 362,                                 // 88,500,000
    TXT_MAP_P26 = 363,                                 // 1,106,000
    TXT_MAP_P27 = 364,                                 // 12,658,000
    TXT_MAP_P28 = 365,                                 // 3,029,000
    TXT_MAP_P29 = 366,                                 // 39,084,000
    TXT_MAP_P30 = 367,                                 // 23,154,000
    TXT_MAP_P31 = 368,                                 // 8,902,000
    TXT_MAP_P32 = 369,                                 // 27,791,000
    TXT_MAP_P33 = 370,                                 // 1,574,000
    TXT_MAP_P34 = 371,                                 // 15,469,000
    TXT_MAP_P35 = 372,                                 // 1,300,000
    TXT_MAP_P36 = 373,                                 // 41,688,000
    TXT_MAP_A00 = 374,                                 // 24,900 SQ. MI.
    TXT_MAP_A01 = 375,                                 // 120,727 SQ. MI.
    TXT_MAP_A02 = 376,                                 // 80,134 SQ. MI.
    TXT_MAP_A03 = 377,                                 // 233,100 SQ. MI.
    TXT_MAP_A04 = 378,                                 // 137,838 SQ. MI.
    TXT_MAP_A05 = 379,                                 // 30,449 SQ. MI.
    TXT_MAP_A06 = 380,                                 // 18,932 SQ. MI.
    TXT_MAP_A07 = 381,                                 // 32,377 SQ. MI.
    TXT_MAP_A08 = 382,                                 // 35,919 SQ. MI.
    TXT_MAP_A09 = 383,                                 // 7,819 SQ. MI.
    TXT_MAP_A10 = 384,                                 // 91,699 SQ. MI.
    TXT_MAP_A11 = 385,                                 // 51,146 SQ. MI.
    TXT_MAP_A12 = 386,                                 // 11,100 SQ. MI.
    TXT_MAP_A13 = 387,                                 // 44,365 SQ. MI.
    TXT_MAP_A14 = 388,                                 // 39,449 SQ. MI.
    TXT_MAP_A15 = 389,                                 // 19,741 SQ. MI.
    TXT_MAP_A16 = 390,                                 // 17,413 SQ. MI.
    TXT_MAP_C00 = 391,                                 // RIGA
    TXT_MAP_C01 = 392,                                 // WARSAW
    TXT_MAP_C02 = 393,                                 // MINSK
    TXT_MAP_C03 = 394,                                 // KIEV
    TXT_MAP_C04 = 395,                                 // BERLIN
    TXT_MAP_C05 = 396,                                 // PRAGUE
    TXT_MAP_C06 = 397,                                 // BRATISLAVA
    TXT_MAP_C07 = 398,                                 // VIENNA
    TXT_MAP_C08 = 399,                                 // BUDAPEST
    TXT_MAP_C09 = 400,                                 // LJUBLJANA
    TXT_MAP_C10 = 401,                                 // BUCHAREST
    TXT_MAP_C11 = 402,                                 // ATHENS
    TXT_MAP_C12 = 403,                                 // TIRANA
    TXT_MAP_C13 = 404,                                 // SOFIA
    TXT_MAP_C14 = 405,                                 // BELGRADE
    TXT_MAP_C15 = 406,                                 // SARAJEVO
    TXT_MAP_C16 = 407,                                 // TALLINN
    TXT_MAP_C17 = 408,                                 // TRIPOLI
    TXT_MAP_C18 = 409,                                 // CAIRO
    TXT_MAP_C19 = 410,                                 // KHARTOUM
    TXT_MAP_C20 = 411,                                 // N'DJAMENA
    TXT_MAP_C21 = 412,                                 // NOUAKCHOTT
    TXT_MAP_C22 = 413,                                 // YAMOUSSOUKRO
    TXT_MAP_C23 = 414,                                 // PORTO-NOVO
    TXT_MAP_C24 = 415,                                 // ABUJA
    TXT_MAP_C25 = 416,                                 // LIBREVILLE
    TXT_MAP_C26 = 417,                                 // YAOUNDE
    TXT_MAP_C27 = 418,                                 // BANGUI
    TXT_MAP_C28 = 419,                                 // KINSHASA
    TXT_MAP_C29 = 420,                                 // CAIRO
    TXT_MAP_C30 = 421,                                 // LUANDA
    TXT_MAP_C31 = 422,                                 // DAR-ES-SALAAM
    TXT_MAP_C32 = 423,                                 // WINDHOEK
    TXT_MAP_C33 = 424,                                 // MAPUTO
    TXT_MAP_C34 = 425,                                 // GABARONE
    TXT_MAP_C35 = 426,                                 // CAPE TOWN
    TXT_MAP_GDP00 = 427,                               // NEGLIGIBLE
    TXT_MAP_GDP01 = 428,                               // $162.7 BLN
    TXT_MAP_GDP02 = 429,                               // $47.6 BLN
    TXT_MAP_GDP03 = 430,                               // $1,131 BLN
    TXT_MAP_GDP04 = 431,                               // $120 BLN
    TXT_MAP_GDP05 = 432,                               // $164 BLN
    TXT_MAP_GDP06 = 433,                               // $60.1 BLN
    TXT_MAP_GDP07 = 434,                               // $21 BLN
    TXT_MAP_GDP08 = 435,                               // $71.9 BLN
    TXT_MAP_GDP09 = 436,                               // $77 BLN
    TXT_MAP_GDP10 = 437,                               // $4.0 BLN
    TXT_MAP_GDP11 = 438,                               // $47.3 BLN
    TXT_MAP_GDP12 = 439,                               // $120.1 BLN
    TXT_MAP_GDP13 = 440,                               // $14.0 BLN
    TXT_MAP_GDP14 = 441,                               // $28.9 BLN
    TXT_MAP_GDP15 = 442,                               // $39.2 BLN
    TXT_MAP_GDP16 = 443,                               // $12.1 BLN
    TXT_MAP_GDP17 = 444,                               // $1.0 BLN
    TXT_MAP_GDP18 = 445,                               // $10.0 BLN
    TXT_MAP_GDP19 = 446,                               // $1.7 BLN
    TXT_MAP_GDP20 = 447,                               // $28.0 BLN
    TXT_MAP_GDP21 = 448,                               // $5.3 BLN
    TXT_MAP_GDP22 = 449,                               // $11.6 BLN
    TXT_MAP_GDP23 = 450,                               // $1.3 BLN
    TXT_MAP_GDP24 = 451,                               // $6.6 BLN
    TXT_MAP_GDP25 = 452,                               // $8.3 BLN
    TXT_MAP_GDP26 = 453,                               // $6.9 BLN
    TXT_MAP_GDP27 = 454,                               // $2.0 BLN
    TXT_MAP_GDP28 = 455,                               // $3.1 BLN
    TXT_MAP_GDP29 = 456,                               // $104.0 BLN
    TXT_MAP_PC00 = 457,                                // JELGAVA
    TXT_MAP_PC01 = 458,                                // GDANSK
    TXT_MAP_PC02 = 459,                                // BYELISTOK
    TXT_MAP_PC03 = 460,                                // BOBYRUSK
    TXT_MAP_PC04 = 461,                                // IVANO-FRANKOVSK
    TXT_MAP_PC05 = 462,                                // HANOVER
    TXT_MAP_PC06 = 463,                                // DRESDEN
    TXT_MAP_PC07 = 464,                                // OSTRAVA
    TXT_MAP_PC08 = 465,                                // BRATISLAVA
    TXT_MAP_PC09 = 466,                                // SALZBURG
    TXT_MAP_PC10 = 467,                                // BUDAPEST
    TXT_MAP_PC11 = 468,                                // TRIESTE
    TXT_MAP_PC12 = 469,                                // ARAD
    TXT_MAP_PC13 = 470,                                // CORINTH
    TXT_MAP_PC14 = 471,                                // SHKODER
    TXT_MAP_PC15 = 472,                                // SOFIA
    TXT_MAP_PC16 = 473,                                // NIS
    TXT_MAP_PC17 = 474,                                // BELGRADE
    TXT_MAP_PC18 = 475,                                // ?
    TXT_MAP_PC19 = 476,                                // PARNU
    TXT_MAP_PC20 = 477,                                // TMASSAH
    TXT_MAP_PC21 = 478,                                // AL-ALAMYN
    TXT_MAP_PC22 = 479,                                // AL-KHARIJAH
    TXT_MAP_PC23 = 480,                                // AL-UBAYYID
    TXT_MAP_PC24 = 481,                                // KAFIA-KINGI
    TXT_MAP_PC25 = 482,                                // OUM HADJER
    TXT_MAP_PC26 = 483,                                // MAO
    TXT_MAP_PC27 = 484,                                // TIDJIKDJA
    TXT_MAP_PC28 = 485,                                // ABIDJAN
    TXT_MAP_PC29 = 486,                                // PORTO-NOVO
    TXT_MAP_PC30 = 487,                                // ABUJA
    TXT_MAP_PC31 = 488,                                // KOULA-MOUTOU
    TXT_MAP_PC32 = 489,                                // BERTOUA
    TXT_MAP_PC33 = 490,                                // BANGASSOU
    TXT_MAP_PC34 = 491,                                // LODJA
    TXT_MAP_PC35 = 492,                                // KINSHASA
    TXT_MAP_PC36 = 493,                                // LUXOR
    TXT_MAP_PC37 = 494,                                // CAIUNDO
    TXT_MAP_PC38 = 495,                                // MZUZU
    TXT_MAP_PC39 = 496,                                // KEETMANSHOOP
    TXT_MAP_PC40 = 497,                                // XAI-XAI
    TXT_MAP_PC41 = 498,                                // GHANZI
    TXT_MAP_PC42 = 499,                                // CAPE TOWN
    TXT_MAP_GDI = 500,                                 // GDI PROGRESSION
    TXT_MAP_NOD = 501,                                 // NOD PROGRESSION
    TXT_MAP_LOCATE = 502,                              // LOCATING COORDINATES
    TXT_MAP_NEXT_MISSION = 503,                        // OF NEXT MISSION
    TXT_MAP_SELECT = 504,                              // SELECT TERRITORY
    TXT_MAP_TO_ATTACK = 505,                           // TO ATTACK
    TXT_MAP_GDISTAT0 = 506,                            // POPULATION:
    TXT_MAP_GDISTAT1 = 507,                            // GEOGRAPHIC AREA:
    TXT_MAP_GDISTAT2 = 508,                            // CAPITAL:
    TXT_MAP_GDISTAT3 = 509,                            // GOVERNMENT:
    TXT_MAP_GDISTAT4 = 510,                            // GROSS DOMESTIC PRODUCT:
    TXT_MAP_GDISTAT5 = 511,                            // POINT OF CONFLICT:
    TXT_MAP_GDISTAT6 = 512,                            // MILITARY POWER:
    TXT_MAP_NODSTAT0 = 513,                            // EXPENDABILITY:
    TXT_MAP_NODSTAT1 = 514,                            // GOVT CORRUPTABILITY:
    TXT_MAP_NODSTAT2 = 515,                            // NET WORTH:
    TXT_MAP_NODSTAT3 = 516,                            // MILITARY STRENGTH:
    TXT_MAP_NODSTAT4 = 517,                            // MILITARY RESISTANCE:
    TXT_MAP_COUNTRYNAME0 = 518,                        // LATVIA
    TXT_MAP_COUNTRYNAME1 = 519,                        // POLAND
    TXT_MAP_COUNTRYNAME2 = 520,                        // BELARUS
    TXT_MAP_COUNTRYNAME3 = 521,                        // UKRAINE
    TXT_MAP_COUNTRYNAME4 = 522,                        // GERMANY
    TXT_MAP_COUNTRYNAME5 = 523,                        // CZECH REPUBLIC
    TXT_MAP_COUNTRYNAME6 = 524,                        // SLOVAKIA
    TXT_MAP_COUNTRYNAME7 = 525,                        // AUSTRIA
    TXT_MAP_COUNTRYNAME8 = 526,                        // HUNGARY
    TXT_MAP_COUNTRYNAME9 = 527,                        // SLOVENIA
    TXT_MAP_COUNTRYNAME10 = 528,                       // ROMANIA
    TXT_MAP_COUNTRYNAME11 = 529,                       // GREECE
    TXT_MAP_COUNTRYNAME12 = 530,                       // ALBANIA
    TXT_MAP_COUNTRYNAME13 = 531,                       // BULGARIA
    TXT_MAP_COUNTRYNAME14 = 532,                       // YUGOSLAVIA
    TXT_MAP_COUNTRYNAME15 = 533,                       // BOSNIA/HERZOGOVINA
    TXT_MAP_COUNTRYNAME16 = 534,                       // LIBYA
    TXT_MAP_COUNTRYNAME17 = 535,                       // EGYPT
    TXT_MAP_COUNTRYNAME18 = 536,                       // SUDAN
    TXT_MAP_COUNTRYNAME19 = 537,                       // CHAD
    TXT_MAP_COUNTRYNAME20 = 538,                       // MAURITANIA
    TXT_MAP_COUNTRYNAME21 = 539,                       // IVORY COAST
    TXT_MAP_COUNTRYNAME22 = 540,                       // BENIN
    TXT_MAP_COUNTRYNAME23 = 541,                       // NIGERIA
    TXT_MAP_COUNTRYNAME24 = 542,                       // GABON
    TXT_MAP_COUNTRYNAME25 = 543,                       // CAMEROON
    TXT_MAP_COUNTRYNAME26 = 544,                       // CENTRAL AFRICAN REPUBLIC
    TXT_MAP_COUNTRYNAME27 = 545,                       // ZAIRE
    TXT_MAP_COUNTRYNAME28 = 546,                       // ANGOLA
    TXT_MAP_COUNTRYNAME29 = 547,                       // TANZANIA
    TXT_MAP_COUNTRYNAME30 = 548,                       // NAMIBIA
    TXT_MAP_COUNTRYNAME31 = 549,                       // MOZAMBIQUE
    TXT_MAP_COUNTRYNAME32 = 550,                       // BOTSWANA
    TXT_MAP_COUNTRYNAME33 = 551,                       // SOUTH AFRICA
    TXT_MAP_COUNTRYNAME34 = 552,                       // ESTONIA
    TXT_MAP_GOVT0 = 553,                               // REPUBLIC
    TXT_MAP_GOVT1 = 554,                               // DEMOCRATIC STATE
    TXT_MAP_GOVT2 = 555,                               // FEDERAL REPUBLIC
    TXT_MAP_GOVT3 = 556,                               // CONST. REPUBLIC
    TXT_MAP_GOVT4 = 557,                               // PARL. DEMOCRACY
    TXT_MAP_GOVT5 = 558,                               // PRES. PARL. REPUBLIC
    TXT_MAP_GOVT6 = 559,                               // DEMOCRACY
    TXT_MAP_GOVT7 = 560,                               // IN TRANSITION
    TXT_MAP_GOVT8 = 561,                               // ISLAMIC SOCIALIST
    TXT_MAP_GOVT9 = 562,                               // MILITARY
    TXT_MAP_GOVT10 = 563,                              // ISLAMIC REPUBLIC
    TXT_MAP_GOVT11 = 564,                              // PARL. REPUBLIC
    TXT_MAP_ARMY0 = 565,                               // LOCAL MILITIA
    TXT_MAP_ARMY1 = 566,                               // STATE MILITIA
    TXT_MAP_ARMY2 = 567,                               // NATIONAL GUARD
    TXT_MAP_ARMY3 = 568,                               // FREE STANDING ARMY
    TXT_MAP_ARMY4 = 569,                               // ?
    TXT_MAP_ARMY5 = 570,                               // NATIONAL POWER
    TXT_MAP_MILITARY0 = 571,                           // RESPECTABLE
    TXT_MAP_MILITARY1 = 572,                           // FORMIDABLE
    TXT_MAP_MILITARY2 = 573,                           // LAUGHABLE
    TXT_MAP_MILITARY3 = 574,                           // REASONABLE
    TXT_MAP_MILITARY4 = 575,                           // INSIGNIFICANT
    TXT_MAP_CLICK2 = 576,                              // CLICK TO CONTINUE
    TXT_MAP_LMH0 = 577,                                // LOW
    TXT_MAP_LMH1 = 578,                                // MEDIUM
    TXT_MAP_LMH2 = 579,                                // HIGH
    TXT_SCORE_TIME = 580,                              // TIME:
    TXT_SCORE_LEAD = 581,                              // LEADERSHIP:
    TXT_SCORE_EFFI = 582,                              // EFFICIENCY:
    TXT_SCORE_TOTA = 583,                              // TOTAL SCORE:
    TXT_SCORE_CASU = 584,                              // CASUALTIES:
    TXT_SCORE_NEUT = 585,                              // NEUTRAL:
    TXT_SCORE_GDI = 586,                               // GDI:
    TXT_SCORE_BUIL = 587,                              // BUILDINGS LOST
    TXT_SCORE_BUIL1 = 588,                             // BUILDINGS
    TXT_SCORE_BUIL2 = 589,                             // LOST:
    TXT_SCORE_TOP = 590,                               // TOP SCORES
    TXT_SCORE_ENDCRED = 591,                           // ENDING CREDITS:
    TXT_SCORE_TIMEFORMAT1 = 592,                       // %dh %dm
    TXT_SCORE_TIMEFORMAT2 = 593,                       // %dm
    TXT_SCORE_NOD = 594,                               // NOD:
    TXT_DIALING = 595,                                 // Dialing...
    TXT_DIALING_CANCELED = 596,                        // Dialing Canceled
    TXT_WAITING_FOR_CALL = 597,                        // Waiting for Call...
    TXT_ANSWERING_CANCELED = 598,                      // Answering Canceled
    TXT_E7 = 599,                                      // Engineer
    TXT_SPECIAL_OPTIONS = 600,                         // Special Options
    TXT_VISIBLE_TARGET = 601,                          // Targeting flash visible to
    TXT_TREE_TARGET = 602,                             // Allow targeting of trees.
    TXT_MCV_DEPLOY = 603,                              // Allow undeploy of
    TXT_SMART_DEFENCE = 604,                           // Employ smarter self defense
    TXT_SLOW_BUILD = 605,                              // Moderate production speed.
    TXT_THREE_POINT = 606,                             // Use three point turn logic.
    TXT_TIBERIUM_GROWTH = 607,                         // Tiberium will grow.
    TXT_TIBERIUM_SPREAD = 608,                         // Tiberium will spread.
    TXT_ROAD_PIECES = 609,                             // Disable building "bib"
    TXT_SCATTER = 610,                                 // Allow running from
    TXT_MODEM_OR_LOOPBACK = 611,                       // Not a Null Modem Cable
    TXT_MAP = 612,                                     // Map
    TXT_FROM_COMPUTER = 613,                           // From Computer:
    TXT_COMP_MSG1 = 614,                               // Prepare to die!
    TXT_COMP_MSG2 = 615,                               // How about a bullet
    TXT_COMP_MSG3 = 616,                               // Incoming!
    TXT_COMP_MSG4 = 617,                               // I see you!
    TXT_COMP_MSG5 = 618,                               // Hey, I'm over here!
    TXT_COMP_MSG6 = 619,                               // Come get some!
    TXT_COMP_MSG7 = 620,                               // I got you!
    TXT_COMP_MSG8 = 621,                               // You humans are never a
    TXT_COMP_MSG9 = 622,                               // Abort, Retry, Ignore? (Ha
    TXT_COMP_MSG10 = 623,                              // Format another? (Just
    TXT_COMP_MSG11 = 624,                              // Beat me and I'll reboot!
    TXT_COMP_MSG12 = 625,                              // You're artificial
    TXT_COMP_MSG13 = 626,                              // My AI is better than your
    TXT_THEME_AIRSTRIKE = 627,                         // Air Strike
    TXT_THEME_HEAVYG = 628,                            // Demolition
    TXT_THEME_J1 = 629,                                // Untamed Land
    TXT_THEME_JDI_V2 = 630,                            // Take 'em Out
    TXT_THEME_RADIO = 631,                             // Radio
    TXT_THEME_RAIN = 632,                              // Rain In The Night
    TXT_THEME_IND2 = 633,                              // Canyon Chase
    TXT_THEME_HEART = 634,                             // Heartbreak
    TXT_BLOSSOM_TREE = 635,                            // Blossom Tree
    TXT_RESTATE_MISSION = 636,                         // Restate
    TXT_COMPUTER = 637,                                // Computer
    TXT_COUNT = 638,                                   // Unit Count:
    TXT_LEVEL = 639,                                   // Tech Level:
    TXT_OPPONENT = 640,                                // Opponent
    TXT_KILLS_COLON = 641,                             // Kills:
    TXT_VIDEO = 642,                                   // Video
    TXT_C10 = 643,                                     // Nikoomba
    TXT_CAPTURE_THE_FLAG = 644,                        // Capture The Flag
    TXT_THEME_VALK = 645,                              // Ride of the Valkyries
    TXT_OBJECTIVE = 646,                               // Mission Objective
    TXT_MISSION = 647,                                 // Mission
    TXT_NO_SAVES = 648,                                // No saved games available.
    TXT_CIVILIAN_BUILDING = 649,                       // Civilian Building
    TXT_TECHNICIAN = 650,                              // Technician
    TXT_VISCEROID = 651,                               // Visceroid
    TXT_NO_SAVELOAD = 652,                             // Save game options are not
    TXT_DEFENDER_ADVANTAGE = 653,                      // Defender has the advantage.
    TXT_SHOW_NAMES = 654,                              // Show true object names.
    TXT_DELPHI = 655,                                  // Agent Delphi
    TXT_TO_REPLAY = 656,                               // Would you like to replay
    TXT_RECONN_TO = 657,                               // Reconnecting to %s.
    TXT_PLEASE_WAIT = 658,                             // Please wait %02d seconds.
    TXT_SURRENDER = 659,                               // Do you wish to surrender?
    TXT_GDI_NAME = 660,                                // GLOBAL DEFENSE INITIATIVE
    TXT_NOD_NAME = 661,                                // BROTHERHOOD OF NOD
    TXT_SEL_TRANS = 662,                               // SELECT TRANSMISSION
    TXT_GAMENAME_MUSTBE_UNIQUE = 663,                  // Your game name must be
    TXT_GAME_IS_CLOSED = 664,                          // Game is closed.
    TXT_NAME_MUSTBE_UNIQUE = 665,                      // Your name must be unique.
    TXT_RECONNECTING_TO = 666,                         // Reconnecting to %s
    TXT_WAITING_FOR_CONNECTIONS = 667,                 // Waiting for connections...
    TXT_TIME_ALLOWED = 668,                            // Time allowed: %02d seconds
    TXT_PRESS_ESC = 669,                               // Press ESC to cancel.
    TXT_JUST_YOU_AND_ME = 670,                         // From Computer: It's just
    TXT_CAPTURE_THE_FLAG_COLON = 671,                  // Capture the Flag:
    TXT_CHAN = 672,                                    // Dr. Chan
    TXT_HAS_ALLIED = 673,                              // %s has allied with %s
    TXT_AT_WAR = 674,                                  // %s declares war on %s
    TXT_SEL_TARGET = 675,                              // Select a target
    TXT_SEPARATE_HELIPAD = 676,                        // Allow separate helipad
    TXT_RESIGN = 677,                                  // Resign Game
    TXT_TIBERIUM_FAST = 678,                           // Tiberium grows quickly.
    TXT_ANSWERING = 679,                               // Answering...
    TXT_INITIALIZING_MODEM = 680,                      // Initializing Modem...
    TXT_SCENARIOS_DO_NOT_MATCH = 681,                  // Scenarios don't match.
    TXT_POWER_OUTPUT = 682,                            // Power Output
    TXT_POWER_OUTPUT_LOW = 683,                        // Power Output (low)
    TXT_CONTINUE = 684,                                // Continue
    TXT_QUEUE_FULL = 685,                              // Data Queue Overflow
    TXT_SPECIAL_WARNING = 686,                         // %s changed game options!
    TXT_CD_DIALOG_1 = 687,                             // Please insert a Command &
    TXT_CD_DIALOG_2 = 688,                             // Please insert CD %d (%s)
    TXT_CD_ERROR1 = 689,                               // Command & Conquer is unable
    TXT_NO_SOUND_CARD = 690,                           // No Sound Card Detected
    TXT_UNKNOWN = 691,                                 // UNKNOWN
    TXT_OLD_GAME = 692,                                // (old)
    TXT_NO_SPACE = 693,                                // Insufficient Disk Space to
    TXT_MUST_HAVE_SPACE = 694,                         // You must have %d megabytes
    TXT_RUN_SETUP = 695,                               // Run SETUP program first.
    TXT_WAITING_FOR_OPPONENT = 696,                    // Waiting for Opponent
    TXT_SELECT_SETTINGS = 697,                         // Please select 'Settings' to
    TXT_PRISON = 698,                                  // Prison
    TXT_GAME_WAS_SAVED = 699,                          // Game Saved
    TXT_SPACE_CANT_SAVE = 700,                         // Insufficient disk space to
    TXT_INVALID_PORT_ADDRESS = 701,                    // Invalid Port/Address. COM
    TXT_INVALID_SETTINGS = 702,                        // Invalid Port and/or IRQ
    TXT_IRQ_ALREADY_IN_USE = 703,                      // IRQ already in use
    TXT_ABORT = 704,                                   // Abort
    TXT_RESTART = 705,                                 // Restart
    TXT_RESTARTING = 706,                              // Mission is
    TXT_LOADING = 707,                                 // Mission is loading. Please
    TXT_ERROR_IN_INITSTRING = 708,                     // Error in the InitString
    TXT_ORDER_INFO = 709,                              // Order Info
    TXT_SCENES = 710,                                  // Scenes
    TXT_NEW_MISSIONS = 711,                            // New Missions
    TXT_THEME_CHRG = 712,                              // Depth Charge
    TXT_THEME_DRON = 713,                              // Drone
    TXT_THEME_FIST = 714,                              // Iron Fist
    TXT_THEME_CREP = 715,                              // Creeping Upon
    TXT_THEME_80MX = 716,                              // C&C 80's Mix
    TXT_THEME_DRIL = 717,                              // Drill
    TXT_CD_DIALOG_3 = 718,                             // Please insert the Covert
    TXT_THEME_RECON = 719,                             // Recon
    TXT_THEME_VOICE = 720,                             // Voice Rhythm
    TXT_ERROR_NO_INIT = 721,                           // Error - modem did not
    TXT_NO_FLOW_CONTROL_RESPONSE = 722,                // Error - Modem failed to
    TXT_NO_COMPRESSION_RESPONSE = 723,                 // Error - Modem failed to
    TXT_NO_ERROR_CORRECTION_RESPONSE = 724,            // Error - Modem failed to
    TXT_ERROR_NO_DISABLE = 725,                        // Error - unable to disable
    TXT_ERROR_TOO_MANY = 726,                          // Error - Too many errors
    TXT_IGNORE = 727,                                  // Ignore
    TXT_CONNECTING = 728,                              // Connecting... Please Wait.
    TXT_EXPLAIN_REGISTRATION = 729,                    // To play Command & Conquer
    TXT_REGISTER = 730,                                // Register
    TXT_ERROR_UNABLE_TO_RUN_WCHAT = 731,               // Wchat not installed. Please
    TXT_INTERNET = 732,                                // Internet Game
    TXT_UNABLE_TO_SET_VIDEO_MODE = 733,                // Error - Unable to set the
    TXT_UNABLE_TO_ALLOCATE_PRIMARY_VIDEO_BUFFER = 734, // Error - Unable to allocate
    TXT_NO_DIAL_TONE = 735,                            // No dial tone. Ensure your
    TXT_MODEM_INITIALISATION = 736,                    // Modem Initialization
    TXT_DATA_COMPRESSION = 737,                        // Data Compression
    TXT_ERROR_CORRECTION = 738,                        // Error Correction
    TXT_HARDWARE_FLOW_CONTROL = 739,                   // Hardware Flow Control
    TXT_ADVANCED = 740,                                // Advanced
    TXT_JUST_INTRO = 741,                              // Intro
    TXT_READING_IMAGE_DATA = 742,                      // READING IMAGE DATA
    TXT_ANALYZING = 743,                               // ANALYZING
    TXT_ENHANCING_IMAGE_DATA = 744,                    // ENHANCING IMAGE DATA
    TXT_ISOLATING_OPERATIONAL_THEATER = 745,           // ISOLATING OPERATIONAL
    TXT_ESTABLISHING_TRADITIONAL_BOUNDARIES = 746,     // ESTABLISHING TRADITIONAL
    TXT_FOR_VISUAL_REFERENCE = 747,                    // FOR VISUAL REFERENCE
    TXT_ENHANCING_IMAGE = 748,                         // ENHANCING IMAGE
    TXT_BONUS_MISSIONS = 749,                          // Bonus Missions
    TXT_BONUS_MISSION_1 = 750,                         // Bonus Mission 1
    TXT_BONUS_MISSION_2 = 751,                         // Bonus Mission 2
    TXT_BONUS_MISSION_3 = 752,                         // Bonus Mission 3
    TXT_BONUS_MISSION_4 = 753,                         // Bonus Mission 4
    TXT_BONUS_MISSION_5 = 754,                         // Bonus Mission 5
}
