use std::ops::Index;

use crate::text::IDs::*;
use crate::theme::{ThemeControl, ThemeType};
use strum::EnumCount;

/// These are the actual filename list for the theme sample files.
pub const _themes: [ThemeControl; ThemeType::COUNT - 1] = [
    ThemeControl::new(
        "AIRSTRIK",
        TXT_THEME_AIRSTRIKE,
        0,
        200,
        false,
        false,
        false,
        true,
    ),
    ThemeControl::new(
        "80MX226M",
        TXT_THEME_80MX,
        0,
        248,
        false,
        false,
        false,
        true,
    ),
    ThemeControl::new("CHRG226M", TXT_THEME_CHRG, 0, 256, true, false, false, true),
    ThemeControl::new("CREP226M", TXT_THEME_CREP, 0, 222, true, false, false, true),
    ThemeControl::new("DRIL226M", TXT_THEME_DRIL, 0, 272, true, false, false, true),
    ThemeControl::new("DRON226M", TXT_THEME_DRON, 0, 275, true, false, false, true),
    ThemeControl::new("FIST226M", TXT_THEME_FIST, 0, 212, true, false, false, true),
    ThemeControl::new(
        "RECN226M",
        TXT_THEME_RECON,
        0,
        261,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new(
        "VOIC226M",
        TXT_THEME_VOICE,
        0,
        306,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new("HEAVYG", TXT_THEME_HEAVYG, 0, 180, true, false, false, true),
    ThemeControl::new("J1", TXT_THEME_J1, 4, 187, true, false, false, true),
    //	ThemeControl::new("J1", TXT_THEME_J1, 4, 187, false, false, false, true),
    ThemeControl::new("JDI_V2", TXT_THEME_JDI_V2, 5, 183, true, false, false, true),
    ThemeControl::new("RADIO", TXT_THEME_RADIO, 6, 183, true, false, false, true),
    ThemeControl::new("RAIN", TXT_THEME_RAIN, 7, 156, true, false, false, true),
    ThemeControl::new("AOI", TXT_THEME_AOI, 0, 168, true, true, false, true),
    ThemeControl::new(
        "CCTHANG",
        TXT_THEME_CCTHANG,
        12,
        193,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new("DIE", TXT_THEME_DIE, 11, 162, false, false, false, true),
    ThemeControl::new("FWP", TXT_THEME_FWP, 10, 53, true, false, false, true),
    ThemeControl::new("IND", TXT_THEME_IND, 1, 175, true, false, false, true),
    ThemeControl::new("IND2", TXT_THEME_IND2, 1, 38, true, false, false, true),
    ThemeControl::new(
        "JUSTDOIT",
        TXT_THEME_JUSTDOIT,
        9,
        142,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new(
        "LINEFIRE",
        TXT_THEME_LINEFIRE,
        8,
        125,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new("MARCH", TXT_THEME_MARCH, 7, 157, true, false, false, true),
    ThemeControl::new("TARGET", TXT_THEME_TARGET, 0, 173, true, false, false, true),
    ThemeControl::new(
        "NOMERCY",
        TXT_THEME_NOMERCY,
        2,
        204,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new("OTP", TXT_THEME_OTP, 3, 182, true, false, false, true),
    ThemeControl::new("PRP", TXT_THEME_PRP, 4, 211, true, false, false, true),
    ThemeControl::new("ROUT", TXT_THEME_ROUT, 12, 121, false, true, false, true),
    ThemeControl::new("HEART", TXT_THEME_HEART, 5, 206, false, true, false, true),
    ThemeControl::new(
        "STOPTHEM",
        TXT_THEME_STOPTHEM,
        0,
        190,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new(
        "TROUBLE",
        TXT_THEME_TROUBLE,
        6,
        191,
        true,
        true,
        false,
        true,
    ),
    ThemeControl::new(
        "WARFARE",
        TXT_THEME_WARFARE,
        0,
        182,
        true,
        false,
        false,
        true,
    ),
    ThemeControl::new(
        "BEFEARED",
        TXT_THEME_BEFEARED,
        13,
        164,
        false,
        true,
        false,
        true,
    ),
    ThemeControl::new("I_AM", TXT_THEME_IAM, 6, 161, false, false, false, true),
    ThemeControl::new("WIN1", TXT_THEME_WIN1, 0, 41, false, true, true, true),
    ThemeControl::new("MAP1", TXT_THEME_WIN1, 0, 61, false, false, true, true),
    ThemeControl::new("VALKYRIE", TXT_THEME_VALK, 0, 306, false, false, true, true),
];

impl Index<ThemeType> for [ThemeControl; ThemeType::COUNT - 1] {
    type Output = ThemeControl;

    fn index(&self, index: ThemeType) -> &Self::Output {
        &self[index as usize]
    }
}
